### PR TITLE
Feature/aws 2.3

### PR DESCRIPTION
**Pull request by jufemaiz**
Right, so, long time no speak. With Tour de France happening and awaiting the arrival of my first child I've had some time to review this.

There has been major changes to the AWS SDK Gem that I've now adopted for this one.
### Major Changes
- Further, code has been moved out of individual bin files and into a more structured Whenever::Elasticbeanstalk class. This has reduced duplication considerably.
- By default, AWS EC2 Instance Credentials are passed as the credentials to use for checking tags etc.
- Roles now include the traditional leader/non-leader in addition to the environmental from RACK_ENV environmental variable.

I've got this working on a staging environment but would like to get some feedback, particularly from @dignoe and @cyborgmaster due to their work.

### CODE REVIEW

**Comment by dignoe** [comment]
I haven't used this gem in years (I've moved to using OpsWorks), so I don't feel that I can add much to this conversation. Please let me know if you need anything though (like github or rubygem permissions), and I'd be happy to help.

**Comment by CyborgMaster** [comment]
@jufemaiz, I really like the approach you've taken here.  Seems like the refactoring is going in a good direction.  I can't say wether it works correctly because the only real way to test it is to run in inside elastic beanstalk in a real instance, but assume it works, I'm all for it.

**Comment by binodmainali** [comment]
I can actually test this out, as I am have one spare Beanstalk instance running for testing. I have commented on an issue. @jufemaiz may be we can get in touch and figure out something

**Comment by jufemaiz** [comment]
@binodmainali1 note the requirements to work with git based gems.

**Comment by dignoe** [comment]
@jufemaiz It looks like you have access on Rubygems to update the packaged gem.

**Comment by jufemaiz** [comment]
@dignoe yep, just wasn't really wanting to push something there without a bit of a review.

For those wanting to test, have a read of https://gist.github.com/jufemaiz/eba1ee62c3709d2db90cc16eb2c5c10b

**Comment by jufemaiz** [comment]
Right I think I'm at a stage to make this a v2.0.0-beta0 release.

Any objections?

**Comment by Drakula2k** [comment]
Hi!

I just tested it with 64bit Amazon Linux 2016.03 v2.1.3 running Ruby 2.3 (Puma) and webapp user's cron gives error `(CRON) ERROR chdir failed (/home/webapp): No such file or directory` on run (on /var/log/cron log).

I investigated it a bit and seems that cron needs user's home directory for internal needs, so I think the easiest workaround is to create it and give access to webapp user.

Also something weird happened to logs, there is a symlinks loop:

```
# ll /var/app/containerfiles/logs/production.log
lrwxrwxrwx 1 webapp webapp 35 Aug 11 13:32 /var/app/containerfiles/logs/production.log -> /var/app/current/log/production.log

#ll /var/app/current/log/development.log
lrwxrwxrwx 1 webapp webapp 36 Aug 11 13:32 /var/app/current/log/development.log -> /var/app/current/log/development.log
```

Seems related to config from Rails + GIT gist.

**Comment by jwilsjustin** [comment]
@jufemaiz Still thinking about a v2.0.0-beta0 release on rubygems.org?

**Comment by jufemaiz** [comment]
Closing this out.

Happy to consider re-opening if people are interested.

I'll write up a better approach to this using Docker and ECS / Fargate if people show interest.

**Pull request closed without merging**
