### PR TITLE
add whenever --roles flag to hide leader-only schedules from non-leaders

### PR DESCRIPTION
**Pull request by obrientimothya**
Without the presence of a '--roles' flag on the second Whenever command, Whenever was generating the same crontab for both instances.
This was causing schedules, tagged with the leader role, to be executed on non-leader elastic beanstalk nodes.

Thanks for your great work, @dignoe

### CODE REVIEW

**Comment by rushilgoel** [comment]
Seems like I'm noticing the same where the jobs that are only supposed to running on the leader are running on the other instances as well.

@obrientimothya I'm not sure if your fix works completely, because wouldn't that require the other instances to be designated with 'non-leader' roles for things to work?

**Comment by obrientimothya** [comment]
@rushilgoel a better fix may be to allow the --roles flag to be passed in as a parameter. However, I did not feel an immediate need to do this, see below:

The way 'whenever' behaves is a bit hard to work with here...
- If no --roles flag at all, then ALL commands (with or without roles) will be scheduled
- if a --roles is passed, then all commands matching the role are scheduled AND those with no role are also scheduled.

Hence, passing a dummy --roles flag (such as non-leader) will result in only the commands with NO role to be scheduled, thus omitting the leader role.

**Comment by dignoe** [comment]
Sorry for the delay... I'm currently out of the country on vacation. I'm fine with using this dummy flag, but also agree that it would be nice to be able to specify a flag using the YAML config file. If there's a pull request with the config file on Monday, I'll merge that; if not, I'll write the change and push early next week.

**Comment by lime** [comment]
A pleasant side effect of this fix is that I can tag a command with `roles: [:non-leader]` to have it run on all instances except the leader. Fits my use case perfectly.

I'm thinking I could add a mention of it in the Readme, making it an actual feature (and lessening the risk of it changing in a future version). Would that be okay?

**Pull request merged**
